name: Sim

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  verilate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup verilator (you can use official package or a setup action)
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install verilator -y

      - name: Run Makefile Sim
        run: |
          make clean
          make sim

      - name: Archive waveform (if any)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: sim-waveforms
          path: obj_dir/**/*.vcd
